version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd ./app-cdk
      - echo Installing npm packages... 
      - npm install
  build:
    commands:
      - echo run tests...
      - pwd
      - ls
      - CI=true npm run test  
